name       : z3          # name of the package
version    : 4.3.0-1     # version of the package
kind       : tool        # one of tool or spec(s)
description: An efficient SMT Solver from Microsoft Research. 

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com



assets:
    - asset   : MAIN
      name: Z3 Binaries for Windows
      url     : https://github.com/Spekl/static-files/releases/download/z3-4.3.0-x86.zip/z3-4.3.0-x86.zip
      platform: windows
        

install:
  - cmd: unzip MAIN
    description: Unpacking Z3...
    platform: windows

